### ISSUE TITLE
Third Party Viewer Directory still states that Black Dragon is using misleading complexity calculations

### ISSUE THREAD

**Issue by NiranV** [secondlife/third-party-viewers#3]
No longer true, hasn't been for 3 years.
https://git.alchemyviewer.org/NiranV.Dean/blackdragon/-/commit/be2f473048aa22fc28a34efa35472c5503e2e00f

The Viewer actually reports the official calculation and only uses it for local performance reports (and not even that anymore since render times broke all of it)

**Comment by vir-linden** [comment]
Updated the listing.
