### ISSUE TITLE
[UPDATE]: Alchemy Viewer Links

### ISSUE THREAD

**Issue by RyeMutt** [secondlife/third-party-viewers#6]
### Viewer Name

Alchemy Viewer

### Details

We'd like the following links updated:

Downloads: `https://www.alchemyviewer.org/downloads`
Source: `https://github.com/AlchemyViewer/Alchemy`
Privacy Policy: `https://www.alchemyviewer.org/privacy-policy`

**Comment by bennettgoble** [comment]
All set: https://wiki.secondlife.com/wiki/Third_Party_Viewer_Directory/Alchemy lmk if there's any more edits that need to be made.
